from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timedelta, timezone
from typing import Any

from app.adapters.ats import CandidateProfile
from app.repositories.interfaces import StoredCandidate


def _history(company: str, title: str, start_year: int, end_year: int | None, location: str) -> dict[str, Any]:
    return {
        "company": company,
        "title": title,
        "start_year": start_year,
        "end_year": end_year,
        "location": location,
    }


def _candidate(
    *,
    candidate_id: str,
    full_name: str,
    current_title: str,
    current_company: str,
    location: str,
    sectors: list[str],
    functions: list[str],
    years_experience: int,
    summary: str,
    skills: list[str],
    employment_history: list[dict[str, Any]],
    confidence_score: float,
    source_type: str = "demo_pool",
) -> dict[str, Any]:
    return {
        "candidate_id": candidate_id,
        "full_name": full_name,
        "current_title": current_title,
        "current_company": current_company,
        "location": location,
        "sectors": sectors,
        "functions": functions,
        "years_experience": years_experience,
        "summary": summary,
        "skills": skills,
        "employment_history": employment_history,
        "confidence_score": confidence_score,
        "source_type": source_type,
        "source_system": "mock-ats",
        "evidence": [
            f"Current title: {current_title}",
            f"Current company: {current_company}",
            f"Focus areas: {', '.join(skills[:3])}",
        ],
        "source_urls": [f"https://demo.local/candidates/{candidate_id}"],
    }


DEMO_CANDIDATES: list[dict[str, Any]] = [
    _candidate(
        candidate_id="cand_001",
        full_name="Olivia Hart",
        current_title="Senior Portfolio Manager, Infrastructure",
        current_company="HarbourVest Infrastructure Partners",
        location="Sydney, Australia",
        sectors=["Infrastructure", "Real Assets", "Funds Management"],
        functions=["Portfolio Management", "Investment", "Governance"],
        years_experience=18,
        summary="Leads Australian infrastructure portfolio construction, manager selection, and portfolio oversight for large institutional mandates across transport, utilities, and digital infrastructure.",
        skills=["Infrastructure investing", "Portfolio construction", "Manager selection", "IC reporting", "Super fund coverage"],
        employment_history=[
            _history("HarbourVest Infrastructure Partners", "Senior Portfolio Manager, Infrastructure", 2021, None, "Sydney"),
            _history("Aware Super", "Portfolio Manager, Real Assets", 2016, 2021, "Sydney"),
            _history("Macquarie Asset Management", "Investment Manager", 2011, 2016, "Sydney"),
        ],
        confidence_score=0.96,
    ),
    _candidate(
        candidate_id="cand_002",
        full_name="Ethan Ng",
        current_title="Infrastructure Investment Director",
        current_company="Macquarie Asset Management",
        location="Melbourne, Australia",
        sectors=["Infrastructure", "Real Assets", "Funds Management"],
        functions=["Investment", "Portfolio Management", "Strategy"],
        years_experience=17,
        summary="Runs infrastructure portfolio strategy and direct investment allocation across Australia and New Zealand with strong portfolio monitoring and capital deployment experience.",
        skills=["Infrastructure investment", "Portfolio strategy", "Capital deployment", "Asset allocation", "Stakeholder management"],
        employment_history=[
            _history("Macquarie Asset Management", "Infrastructure Investment Director", 2020, None, "Melbourne"),
            _history("QIC", "Associate Director, Infrastructure", 2014, 2020, "Brisbane"),
            _history("Deloitte", "Infrastructure Advisory Manager", 2009, 2014, "Melbourne"),
        ],
        confidence_score=0.94,
    ),
    _candidate(
        candidate_id="cand_003",
        full_name="Sophie Bennett",
        current_title="Real Assets Director",
        current_company="AustralianSuper",
        location="Melbourne, Australia",
        sectors=["Real Assets", "Infrastructure", "Superannuation"],
        functions=["Portfolio Management", "Governance", "Strategy"],
        years_experience=19,
        summary="Directs real assets portfolio oversight for a major super fund, including infrastructure mandate design, governance packs, and external manager reviews.",
        skills=["Real assets", "Infrastructure mandates", "Governance", "Board reporting", "External manager oversight"],
        employment_history=[
            _history("AustralianSuper", "Real Assets Director", 2022, None, "Melbourne"),
            _history("AustralianSuper", "Senior Portfolio Manager", 2017, 2022, "Melbourne"),
            _history("IFM Investors", "Investment Director", 2011, 2017, "Melbourne"),
        ],
        confidence_score=0.95,
    ),
    _candidate(
        candidate_id="cand_004",
        full_name="Liam O'Connor",
        current_title="Portfolio Oversight Lead",
        current_company="Aware Super",
        location="Sydney, Australia",
        sectors=["Infrastructure", "Superannuation", "Real Assets"],
        functions=["Portfolio Management", "Governance", "Operations"],
        years_experience=16,
        summary="Owns portfolio oversight and performance governance for infrastructure and private markets managers, with direct responsibility for Australian portfolio reviews and remediation actions.",
        skills=["Portfolio oversight", "Performance monitoring", "Risk governance", "Manager review", "Operating model"],
        employment_history=[
            _history("Aware Super", "Portfolio Oversight Lead", 2021, None, "Sydney"),
            _history("HESTA", "Senior Manager, Investment Governance", 2016, 2021, "Melbourne"),
            _history("PwC", "Manager, Investment Advisory", 2011, 2016, "Sydney"),
        ],
        confidence_score=0.92,
    ),
    _candidate(
        candidate_id="cand_005",
        full_name="Grace Wu",
        current_title="Infrastructure Portfolio Manager",
        current_company="IFM Investors",
        location="Sydney, Australia",
        sectors=["Infrastructure", "Funds Management", "Superannuation"],
        functions=["Portfolio Management", "Investment"],
        years_experience=14,
        summary="Manages core infrastructure portfolio sleeves for institutional investors with strong exposure to airports, toll roads, and regulated utilities in Australia.",
        skills=["Institutional portfolio management", "Infrastructure assets", "Client reporting", "Scenario analysis", "Asset reviews"],
        employment_history=[
            _history("IFM Investors", "Infrastructure Portfolio Manager", 2020, None, "Sydney"),
            _history("First Sentier Investors", "Investment Manager", 2015, 2020, "Sydney"),
            _history("AMP Capital", "Infrastructure Analyst", 2012, 2015, "Sydney"),
        ],
        confidence_score=0.93,
    ),
    _candidate(
        candidate_id="cand_006",
        full_name="Noah Sinclair",
        current_title="Director, Infrastructure Portfolio Strategy",
        current_company="QIC",
        location="Brisbane, Australia",
        sectors=["Infrastructure", "Real Assets", "Government"],
        functions=["Strategy", "Portfolio Management", "Investment"],
        years_experience=15,
        summary="Shapes infrastructure portfolio strategy for long-term capital, blending sector allocation, pacing, and asset oversight across transport and energy transition investments.",
        skills=["Portfolio strategy", "Infrastructure allocation", "Energy transition", "Pacing", "Investment committee"],
        employment_history=[
            _history("QIC", "Director, Infrastructure Portfolio Strategy", 2022, None, "Brisbane"),
            _history("Queensland Treasury", "Principal Investment Manager", 2017, 2022, "Brisbane"),
            _history("KPMG", "Infrastructure Advisory Manager", 2012, 2017, "Brisbane"),
        ],
        confidence_score=0.9,
    ),
    _candidate(
        candidate_id="cand_007",
        full_name="Chloe Fraser",
        current_title="Head of Infrastructure Portfolio Management",
        current_company="Future Fund",
        location="Melbourne, Australia",
        sectors=["Infrastructure", "Real Assets", "Government"],
        functions=["Portfolio Management", "Governance", "Strategy"],
        years_experience=20,
        summary="Leads infrastructure portfolio management for a sovereign-style investor, covering allocation, manager governance, and long-duration asset portfolio design.",
        skills=["Portfolio leadership", "Manager governance", "Allocation design", "Real assets", "Institutional mandates"],
        employment_history=[
            _history("Future Fund", "Head of Infrastructure Portfolio Management", 2021, None, "Melbourne"),
            _history("CPPIB", "Principal, Infrastructure", 2015, 2021, "London"),
            _history("Morgan Stanley", "Executive Director, Infrastructure", 2009, 2015, "London"),
        ],
        confidence_score=0.97,
    ),
    _candidate(
        candidate_id="cand_008",
        full_name="Arjun Mehta",
        current_title="Senior Portfolio Manager, Real Assets",
        current_company="First Sentier Investors",
        location="Singapore",
        sectors=["Real Assets", "Infrastructure", "Funds Management"],
        functions=["Portfolio Management", "Investment", "Strategy"],
        years_experience=16,
        summary="Regional real assets portfolio manager with heavy infrastructure allocation experience and prior Australian institutional client coverage.",
        skills=["Real assets", "Infrastructure allocation", "Institutional clients", "Regional portfolio management", "Asset allocation"],
        employment_history=[
            _history("First Sentier Investors", "Senior Portfolio Manager, Real Assets", 2023, None, "Singapore"),
            _history("AMP Capital", "Portfolio Manager, Infrastructure", 2017, 2023, "Sydney"),
            _history("GIC", "Investment Manager", 2012, 2017, "Singapore"),
        ],
        confidence_score=0.88,
    ),
    _candidate(
        candidate_id="cand_009",
        full_name="Mia Lawson",
        current_title="Director, Asset Management and Real Assets Strategy",
        current_company="CBUS Super",
        location="Melbourne, Australia",
        sectors=["Real Assets", "Superannuation", "Infrastructure"],
        functions=["Strategy", "Portfolio Management", "Governance"],
        years_experience=15,
        summary="Blends asset management and real assets strategy across infrastructure, property, and private markets with credible portfolio governance exposure.",
        skills=["Asset management", "Real assets strategy", "Portfolio governance", "Stakeholder alignment", "Committee papers"],
        employment_history=[
            _history("CBUS Super", "Director, Asset Management and Real Assets Strategy", 2022, None, "Melbourne"),
            _history("Vicinity", "Strategy Manager", 2018, 2022, "Melbourne"),
            _history("EY", "Infrastructure Advisory Manager", 2013, 2018, "Melbourne"),
        ],
        confidence_score=0.84,
    ),
    _candidate(
        candidate_id="cand_010",
        full_name="Benjamin Clarke",
        current_title="Investment Director, Infrastructure Funds",
        current_company="Global Infrastructure Partners",
        location="London, United Kingdom",
        sectors=["Infrastructure", "Funds Management", "Advisory"],
        functions=["Investment", "Strategy", "Portfolio Management"],
        years_experience=18,
        summary="Infrastructure funds leader covering portfolio construction, fundraising strategy, and board-level asset oversight, with previous APAC infrastructure exposure.",
        skills=["Infrastructure funds", "Portfolio construction", "Asset oversight", "Fundraising", "APAC coverage"],
        employment_history=[
            _history("Global Infrastructure Partners", "Investment Director, Infrastructure Funds", 2021, None, "London"),
            _history("Morgan Stanley Infrastructure Partners", "Principal", 2014, 2021, "London"),
            _history("Macquarie Asset Management", "Associate Director", 2009, 2014, "Sydney"),
        ],
        confidence_score=0.83,
    ),
    _candidate(
        candidate_id="cand_011",
        full_name="Hannah Park",
        current_title="Asset Management Manager",
        current_company="Plenary Group",
        location="Sydney, Australia",
        sectors=["Infrastructure", "Advisory", "Government"],
        functions=["Operations", "Governance", "Strategy"],
        years_experience=13,
        summary="Manages operational asset oversight for PPP and infrastructure assets, including reporting, performance improvement, and interface with investors and government stakeholders.",
        skills=["Asset management", "PPP operations", "Performance reporting", "Stakeholder management", "Governance"],
        employment_history=[
            _history("Plenary Group", "Asset Management Manager", 2021, None, "Sydney"),
            _history("NSW Treasury", "Infrastructure Manager", 2016, 2021, "Sydney"),
            _history("Jacobs", "Consultant", 2012, 2016, "Sydney"),
        ],
        confidence_score=0.79,
    ),
    _candidate(
        candidate_id="cand_012",
        full_name="Jack Turner",
        current_title="Real Assets Strategy Manager",
        current_company="Hostplus",
        location="Melbourne, Australia",
        sectors=["Real Assets", "Superannuation", "Infrastructure"],
        functions=["Strategy", "Governance"],
        years_experience=12,
        summary="Supports portfolio strategy and thematic reviews across real assets, including infrastructure pacing, manager research, and governance materials for the investment committee.",
        skills=["Real assets strategy", "Manager research", "Pacing", "Investment committee", "Thematic reviews"],
        employment_history=[
            _history("Hostplus", "Real Assets Strategy Manager", 2022, None, "Melbourne"),
            _history("Mercer", "Investment Associate", 2018, 2022, "Melbourne"),
            _history("Aon", "Analyst", 2014, 2018, "Melbourne"),
        ],
        confidence_score=0.8,
    ),
    _candidate(
        candidate_id="cand_013",
        full_name="Priya Raman",
        current_title="Investment Operations Lead",
        current_company="Australian Retirement Trust",
        location="Brisbane, Australia",
        sectors=["Superannuation", "Funds Management"],
        functions=["Operations", "Governance"],
        years_experience=11,
        summary="Leads investment operations for private markets and real assets portfolios, with strong exposure to portfolio data, manager onboarding, and mandate monitoring.",
        skills=["Investment operations", "Manager onboarding", "Portfolio reporting", "Private markets operations", "Data governance"],
        employment_history=[
            _history("Australian Retirement Trust", "Investment Operations Lead", 2021, None, "Brisbane"),
            _history("QSuper", "Operations Manager", 2017, 2021, "Brisbane"),
            _history("State Street", "Senior Analyst", 2014, 2017, "Brisbane"),
        ],
        confidence_score=0.76,
    ),
    _candidate(
        candidate_id="cand_014",
        full_name="Lucas Pereira",
        current_title="Infrastructure Associate Director",
        current_company="KPMG Infrastructure Advisory",
        location="Sydney, Australia",
        sectors=["Infrastructure", "Advisory", "Government"],
        functions=["Strategy", "Investment"],
        years_experience=10,
        summary="Infrastructure advisor focused on investment cases, portfolio reviews, and transaction support for public and institutional infrastructure clients.",
        skills=["Infrastructure advisory", "Investment cases", "Portfolio reviews", "Transactions", "Client management"],
        employment_history=[
            _history("KPMG Infrastructure Advisory", "Infrastructure Associate Director", 2023, None, "Sydney"),
            _history("PwC", "Manager, Infrastructure Advisory", 2018, 2023, "Sydney"),
            _history("Transport for NSW", "Analyst", 2015, 2018, "Sydney"),
        ],
        confidence_score=0.74,
    ),
    _candidate(
        candidate_id="cand_015",
        full_name="Emma Shaw",
        current_title="Investment Manager, Real Assets",
        current_company="Rest Super",
        location="Sydney, Australia",
        sectors=["Real Assets", "Superannuation", "Infrastructure"],
        functions=["Investment", "Governance", "Portfolio Management"],
        years_experience=12,
        summary="Covers manager research and ongoing portfolio monitoring across real assets with specific exposure to infrastructure co-investments and manager governance.",
        skills=["Manager research", "Portfolio monitoring", "Co-investments", "Governance", "Real assets"],
        employment_history=[
            _history("Rest Super", "Investment Manager, Real Assets", 2021, None, "Sydney"),
            _history("AMP Capital", "Senior Analyst", 2017, 2021, "Sydney"),
            _history("JLL", "Analyst", 2014, 2017, "Sydney"),
        ],
        confidence_score=0.82,
    ),
    _candidate(
        candidate_id="cand_016",
        full_name="Daniel Foster",
        current_title="Senior Manager, Investment Governance",
        current_company="HESTA",
        location="Melbourne, Australia",
        sectors=["Superannuation", "Governance", "Real Assets"],
        functions=["Governance", "Operations"],
        years_experience=14,
        summary="Owns investment governance frameworks, manager monitoring, and committee materials across alternative and real assets portfolios.",
        skills=["Investment governance", "Manager monitoring", "Committee papers", "Controls", "Alternatives"],
        employment_history=[
            _history("HESTA", "Senior Manager, Investment Governance", 2020, None, "Melbourne"),
            _history("AustralianSuper", "Manager, Governance", 2015, 2020, "Melbourne"),
            _history("NAB Asset Servicing", "Analyst", 2011, 2015, "Melbourne"),
        ],
        confidence_score=0.77,
    ),
    _candidate(
        candidate_id="cand_017",
        full_name="Amelia Scott",
        current_title="Portfolio Analytics Lead, Private Markets",
        current_company="Aware Super",
        location="Sydney, Australia",
        sectors=["Superannuation", "Funds Management", "Real Assets"],
        functions=["Operations", "Strategy", "Governance"],
        years_experience=11,
        summary="Leads portfolio analytics and oversight tooling for private markets and infrastructure mandates, providing insight to portfolio managers and governance forums.",
        skills=["Portfolio analytics", "Infrastructure reporting", "Data models", "Governance support", "Private markets"],
        employment_history=[
            _history("Aware Super", "Portfolio Analytics Lead, Private Markets", 2022, None, "Sydney"),
            _history("Mercer", "Investment Consultant", 2018, 2022, "Sydney"),
            _history("JPMorgan", "Analyst", 2015, 2018, "Sydney"),
        ],
        confidence_score=0.73,
    ),
    _candidate(
        candidate_id="cand_018",
        full_name="Samuel Brooks",
        current_title="Senior Investment Associate, Infrastructure",
        current_company="QIC",
        location="Brisbane, Australia",
        sectors=["Infrastructure", "Real Assets", "Government"],
        functions=["Investment", "Strategy"],
        years_experience=9,
        summary="Infrastructure associate supporting investment underwriting, portfolio reviews, and asset monitoring across renewable energy, transport, and utilities.",
        skills=["Underwriting", "Asset monitoring", "Infrastructure research", "Valuation", "Portfolio reviews"],
        employment_history=[
            _history("QIC", "Senior Investment Associate, Infrastructure", 2022, None, "Brisbane"),
            _history("KPMG", "Senior Analyst", 2018, 2022, "Brisbane"),
            _history("Queensland Treasury", "Analyst", 2016, 2018, "Brisbane"),
        ],
        confidence_score=0.75,
    ),
    _candidate(
        candidate_id="cand_019",
        full_name="Ella James",
        current_title="Manager, Distribution Strategy",
        current_company="Pendal Group",
        location="Sydney, Australia",
        sectors=["Funds Management", "Distribution"],
        functions=["Distribution", "Strategy"],
        years_experience=10,
        summary="Distribution strategy manager for wholesale and institutional channels with no direct infrastructure portfolio management remit.",
        skills=["Distribution strategy", "Client segmentation", "Product positioning", "Sales enablement"],
        employment_history=[
            _history("Pendal Group", "Manager, Distribution Strategy", 2022, None, "Sydney"),
            _history("BT", "Business Development Manager", 2018, 2022, "Sydney"),
            _history("AMP", "Associate", 2015, 2018, "Sydney"),
        ],
        confidence_score=0.51,
    ),
    _candidate(
        candidate_id="cand_020",
        full_name="Ryan Mitchell",
        current_title="Construction Project Manager",
        current_company="Lendlease",
        location="Brisbane, Australia",
        sectors=["Infrastructure", "Government"],
        functions=["Operations"],
        years_experience=12,
        summary="Construction project manager delivering transport and social infrastructure builds; relevant sector language but not an investment or portfolio management profile.",
        skills=["Project delivery", "Construction", "Stakeholder coordination", "Capital projects"],
        employment_history=[
            _history("Lendlease", "Construction Project Manager", 2021, None, "Brisbane"),
            _history("John Holland", "Project Manager", 2016, 2021, "Brisbane"),
            _history("AECOM", "Engineer", 2012, 2016, "Brisbane"),
        ],
        confidence_score=0.42,
    ),
    _candidate(
        candidate_id="cand_021",
        full_name="Zoe Kim",
        current_title="IT Infrastructure Manager",
        current_company="Telstra",
        location="Melbourne, Australia",
        sectors=["Technology"],
        functions=["Operations"],
        years_experience=13,
        summary="Runs enterprise IT infrastructure and cloud operations, which is clearly different from infrastructure investing despite overlapping terminology.",
        skills=["Cloud operations", "IT infrastructure", "Vendor management", "Cyber resilience"],
        employment_history=[
            _history("Telstra", "IT Infrastructure Manager", 2020, None, "Melbourne"),
            _history("ANZ", "Platform Manager", 2016, 2020, "Melbourne"),
            _history("IBM", "Systems Engineer", 2011, 2016, "Melbourne"),
        ],
        confidence_score=0.33,
    ),
    _candidate(
        candidate_id="cand_022",
        full_name="Nathan Cole",
        current_title="Wealth Platform Product Manager",
        current_company="Hub24",
        location="Sydney, Australia",
        sectors=["Funds Management", "Technology"],
        functions=["Strategy", "Operations"],
        years_experience=9,
        summary="Product manager for wealth platform capabilities with financial services exposure but no relevant infrastructure or real assets portfolio mandate.",
        skills=["Product management", "Platform strategy", "Stakeholder discovery", "Delivery"],
        employment_history=[
            _history("Hub24", "Wealth Platform Product Manager", 2022, None, "Sydney"),
            _history("Netwealth", "Senior Business Analyst", 2018, 2022, "Melbourne"),
            _history("Colonial First State", "Analyst", 2016, 2018, "Sydney"),
        ],
        confidence_score=0.36,
    ),
    _candidate(
        candidate_id="cand_023",
        full_name="Isabella Reed",
        current_title="Compliance Manager",
        current_company="AMP Capital",
        location="Sydney, Australia",
        sectors=["Funds Management"],
        functions=["Governance"],
        years_experience=11,
        summary="Compliance leader in funds management with strong governance process expertise but limited portfolio construction or infrastructure mandate ownership.",
        skills=["Compliance", "Regulatory reporting", "Controls", "Risk management"],
        employment_history=[
            _history("AMP Capital", "Compliance Manager", 2021, None, "Sydney"),
            _history("Perpetual", "Risk Manager", 2017, 2021, "Sydney"),
            _history("ASIC", "Analyst", 2014, 2017, "Sydney"),
        ],
        confidence_score=0.45,
    ),
    _candidate(
        candidate_id="cand_024",
        full_name="Henry Walsh",
        current_title="Distribution Manager, Institutional",
        current_company="Schroders",
        location="Singapore",
        sectors=["Funds Management", "Distribution"],
        functions=["Distribution"],
        years_experience=10,
        summary="Institutional distribution manager covering APAC consultant and client relationships, not a portfolio management or infrastructure investing profile.",
        skills=["Institutional sales", "Consultant coverage", "Client relationships", "RFPs"],
        employment_history=[
            _history("Schroders", "Distribution Manager, Institutional", 2023, None, "Singapore"),
            _history("PIMCO", "Account Manager", 2019, 2023, "Singapore"),
            _history("BlackRock", "Sales Associate", 2016, 2019, "Singapore"),
        ],
        confidence_score=0.39,
    ),
    _candidate(
        candidate_id="cand_025",
        full_name="Ava Hughes",
        current_title="Director, Government Infrastructure Policy",
        current_company="Infrastructure NSW",
        location="Sydney, Australia",
        sectors=["Government", "Infrastructure"],
        functions=["Strategy", "Governance"],
        years_experience=14,
        summary="Government infrastructure policy leader with strategy and stakeholder depth, but not a buy-side portfolio manager or investment director.",
        skills=["Infrastructure policy", "Stakeholder engagement", "Government strategy", "Program design"],
        employment_history=[
            _history("Infrastructure NSW", "Director, Government Infrastructure Policy", 2021, None, "Sydney"),
            _history("NSW Treasury", "Senior Manager", 2016, 2021, "Sydney"),
            _history("Deloitte", "Consultant", 2012, 2016, "Sydney"),
        ],
        confidence_score=0.56,
    ),
    _candidate(
        candidate_id="cand_026",
        full_name="Marcus Lim",
        current_title="Portfolio Manager, Private Markets",
        current_company="GIC",
        location="Singapore",
        sectors=["Real Assets", "Funds Management"],
        functions=["Portfolio Management", "Investment"],
        years_experience=13,
        summary="Private markets portfolio manager with adjacent real assets exposure and selective infrastructure sleeves, though Australia-specific operating context is limited.",
        skills=["Private markets", "Portfolio management", "Asset allocation", "Real assets", "Committee materials"],
        employment_history=[
            _history("GIC", "Portfolio Manager, Private Markets", 2022, None, "Singapore"),
            _history("Temasek", "Investment Manager", 2018, 2022, "Singapore"),
            _history("UBS", "Associate", 2014, 2018, "Singapore"),
        ],
        confidence_score=0.71,
    ),
    _candidate(
        candidate_id="cand_027",
        full_name="Charlotte Evans",
        current_title="Director, Infrastructure Advisory",
        current_company="EY",
        location="London, United Kingdom",
        sectors=["Infrastructure", "Advisory", "Government"],
        functions=["Strategy", "Governance", "Investment"],
        years_experience=15,
        summary="Advises on infrastructure portfolios, governance, and asset strategy for public and institutional clients; credible adjacent experience but not a direct owner-operator portfolio manager.",
        skills=["Infrastructure advisory", "Portfolio reviews", "Governance", "Asset strategy", "Transactions"],
        employment_history=[
            _history("EY", "Director, Infrastructure Advisory", 2021, None, "London"),
            _history("KPMG", "Senior Manager", 2016, 2021, "London"),
            _history("HM Treasury", "Policy Adviser", 2011, 2016, "London"),
        ],
        confidence_score=0.68,
    ),
    _candidate(
        candidate_id="cand_028",
        full_name="Leo Martin",
        current_title="Asset Oversight Manager",
        current_company="NSW Treasury",
        location="Sydney, Australia",
        sectors=["Government", "Infrastructure"],
        functions=["Governance", "Operations", "Strategy"],
        years_experience=12,
        summary="Leads oversight of government-held infrastructure assets and PPP exposures, bringing strong governance and monitoring but limited direct portfolio construction experience.",
        skills=["Asset oversight", "PPP governance", "Performance monitoring", "Government stakeholders"],
        employment_history=[
            _history("NSW Treasury", "Asset Oversight Manager", 2022, None, "Sydney"),
            _history("Infrastructure NSW", "Manager", 2018, 2022, "Sydney"),
            _history("PwC", "Consultant", 2014, 2018, "Sydney"),
        ],
        confidence_score=0.7,
    ),
    _candidate(
        candidate_id="cand_029",
        full_name="Nina D'Souza",
        current_title="Senior Manager, Real Assets Research",
        current_company="Mercer",
        location="Melbourne, Australia",
        sectors=["Real Assets", "Advisory", "Superannuation"],
        functions=["Strategy", "Investment", "Governance"],
        years_experience=13,
        summary="Research lead covering infrastructure and real assets managers for institutional clients, with strong market mapping and manager selection insight.",
        skills=["Manager research", "Real assets", "Infrastructure managers", "Institutional advice", "Due diligence"],
        employment_history=[
            _history("Mercer", "Senior Manager, Real Assets Research", 2021, None, "Melbourne"),
            _history("Willis Towers Watson", "Research Manager", 2017, 2021, "Melbourne"),
            _history("Frontier Advisors", "Analyst", 2013, 2017, "Melbourne"),
        ],
        confidence_score=0.78,
    ),
    _candidate(
        candidate_id="cand_030",
        full_name="Oscar Bell",
        current_title="Portfolio Governance Director",
        current_company="Australian Retirement Trust",
        location="Brisbane, Australia",
        sectors=["Superannuation", "Real Assets", "Infrastructure"],
        functions=["Governance", "Portfolio Management", "Operations"],
        years_experience=17,
        summary="Senior governance leader overseeing infrastructure and private markets portfolios, balancing manager oversight, performance review, and portfolio risk escalation.",
        skills=["Portfolio governance", "Manager oversight", "Performance review", "Risk escalation", "Private markets"],
        employment_history=[
            _history("Australian Retirement Trust", "Portfolio Governance Director", 2022, None, "Brisbane"),
            _history("SunSuper", "Senior Manager, Alternatives", 2017, 2022, "Brisbane"),
            _history("KPMG", "Manager", 2012, 2017, "Brisbane"),
        ],
        confidence_score=0.81,
    ),
]


def load_demo_candidates() -> list[dict[str, Any]]:
    return [deepcopy(candidate) for candidate in DEMO_CANDIDATES]


def enrich_with_demo_fields(candidate: dict[str, Any], demo_lookup: dict[str, dict[str, Any]]) -> dict[str, Any]:
    enriched = deepcopy(candidate)
    candidate_id = candidate.get("candidate_id")
    demo_candidate = demo_lookup.get(candidate_id) if isinstance(candidate_id, str) else None
    if demo_candidate:
        merged = deepcopy(demo_candidate)
        merged.update({k: v for k, v in candidate.items() if v not in (None, "", [], {})})
        enriched = merged

    enriched.setdefault("current_company", "Demo Company")
    enriched.setdefault("location", "Australia")
    enriched.setdefault("sectors", [])
    enriched.setdefault("functions", [])
    enriched.setdefault("skills", [])
    enriched.setdefault("employment_history", [])
    enriched.setdefault("evidence", [])
    enriched.setdefault("source_urls", [])
    enriched.setdefault("source_type", "demo_pool")
    enriched.setdefault("source_system", "mock-ats")
    if enriched.get("confidence_score") is None:
        enriched["confidence_score"] = 0.65
    return enriched


def build_mock_ats_profiles(tenant_id: str = "demo-tenant") -> list[CandidateProfile]:
    base_time = datetime(2026, 3, 14, 0, 0, tzinfo=timezone.utc)
    profiles: list[CandidateProfile] = []
    for index, candidate in enumerate(DEMO_CANDIDATES):
        profiles.append(
            CandidateProfile(
                tenant_id=tenant_id,
                candidate_id=candidate["candidate_id"],
                full_name=candidate["full_name"],
                current_title=candidate["current_title"],
                current_company=candidate["current_company"],
                location=candidate["location"],
                primary_email=f"{candidate['candidate_id']}@demo.local",
                application_ids=[f"app-{1000 + index}"],
                tag_names=list(dict.fromkeys(candidate["sectors"] + candidate["functions"] + candidate["skills"][:3])),
                attachment_count=1 + (index % 3),
                source_system="mock-ats",
                source_id=candidate["candidate_id"],
                synced_at=base_time + timedelta(minutes=index),
            )
        )
    return profiles


def to_stored_candidates(tenant_id: str) -> list[StoredCandidate]:
    base_time = datetime(2026, 3, 14, 0, 0, tzinfo=timezone.utc)
    stored: list[StoredCandidate] = []
    for index, candidate in enumerate(DEMO_CANDIDATES):
        stored.append(
            StoredCandidate(
                tenant_id=tenant_id,
                candidate_id=candidate["candidate_id"],
                full_name=candidate["full_name"],
                current_title=candidate["current_title"],
                current_company=candidate["current_company"],
                location=candidate["location"],
                primary_email=f"{candidate['candidate_id']}@demo.local",
                summary=candidate["summary"],
                evidence=list(candidate["evidence"]),
                source_system="mock-ats",
                source_id=candidate["candidate_id"],
                application_ids=[f"app-{1000 + index}"],
                tag_names=list(dict.fromkeys(candidate["sectors"] + candidate["functions"] + candidate["skills"][:3])),
                attachment_count=1 + (index % 3),
                synced_at=(base_time + timedelta(minutes=index)).isoformat(),
            )
        )
    return stored
